import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/utils/cn";

export const metadata: Metadata = {
  title: "Unides Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-primary flex justify-center items-center",)}>
        {children}
      </body>
    </html>
  );
}
